## Data Cleaning

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("First Dataset.xlsx")
df.to_csv("First Dataset.csv", index=False)

In [5]:
df = pd.read_csv("First Dataset.csv")

In [6]:
clean_df = df.copy()

In [7]:
clean_df.shape

(61, 17)

In [8]:
clean_df.dtypes

customer_id             int64
first_name             object
gender                 object
age                   float64
city                   object
province               object
signup_date            object
membership_tier        object
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method         object
device                 object
discount_used          object
returned_items          int64
satisfaction_score      int64
dtype: object

In [9]:
clean_df["age"].unique()

array([ 19.,  53.,  31.,  58.,  28.,  43.,  23.,  61., 145.,  41.,  51.,
        39.,  35.,  47.,  45.,  49.,  30.,  22.,  nan,  50.,  60.,  37.,
        25.,  34.,  63.,  26.,  42.,  65.,  64.,  54.,  32.,  48.,  59.,
        62.,  57.])

In [10]:
clean_df[clean_df["age"] ==145]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [11]:
clean_df["age"] = clean_df["age"].astype("Int64")

In [12]:
clean_df.loc[clean_df["age"] > 100, "age"] = np.nan

In [13]:
clean_df[clean_df["age"] > 100]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [14]:
clean_df["discount_used"].unique()

array(['Yes', 'No'], dtype=object)

In [15]:
clean_df["discount_used"] = clean_df["discount_used"].map({
    "Yes": True,
    "No": False
})

In [16]:
df["signup_date"].head(10)

0    2025-02-19
1    2022-08-19
2    2023-06-20
3    2021-11-08
4    2021-10-21
5    2022-01-26
6    2025-09-09
7    2024-10-03
8    2021-05-14
9    2022-06-25
Name: signup_date, dtype: object

In [17]:
df["signup_date"].str.match(r"^\d{4}-\d{2}-\d{2}$").value_counts()

signup_date
True    61
Name: count, dtype: int64

In [18]:
clean_df["signup_date"] = pd.to_datetime(clean_df["signup_date"])

In [19]:
clean_df[["age", "discount_used", "signup_date"]].dtypes

age                       Int64
discount_used              bool
signup_date      datetime64[ns]
dtype: object

In [20]:
clean_df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   2
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [21]:
clean_df[clean_df["age"].isna() | clean_df["total_spending"].isna()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,<NA>,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,False,7,1
19,1020,Kimia,M,<NA>,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,True,1,5
39,1040,Amir,F,65,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,True,3,2

In [22]:
clean_df["age"] = clean_df["age"].fillna(
    clean_df["age"].median()
).astype(int)

In [23]:
check = (clean_df["purchase_count"] * clean_df["avg_order_value"]).round(2) == clean_df["total_spending"].round(2)
clean_df[~check]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,True,4,4
39,1040,Amir,F,65,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,True,3,2

In [24]:
calculated = (clean_df["purchase_count"] * clean_df["avg_order_value"]).round(2)

mask = (
    clean_df["total_spending"].isna()
    | (clean_df["total_spending"].round(2) != calculated)
)

clean_df.loc[mask, "total_spending"] = calculated[mask]

In [25]:
check = (clean_df["purchase_count"] * clean_df["avg_order_value"]).round(2) == clean_df["total_spending"].round(2)
clean_df[~check]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [26]:
clean_df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [27]:
clean_df.duplicated().sum()

np.int64(1)

In [28]:
clean_df[clean_df.duplicated(keep=False)]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,False,5,4
60,1014,Reza,M,35,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,False,5,4

In [29]:
clean_df = clean_df.drop_duplicates()

In [30]:
clean_df.duplicated().sum()

np.int64(0)

In [31]:
text_cols = [
    "first_name",
    "gender",
    "city",
    "province",
    "membership_tier",
    "payment_method",
    "device",
    "discount_used"
]

for col in text_cols:
    original = clean_df[col].dropna().astype(str)
    normalized = original.str.strip().str.lower()

    print(
        f"{col}: "
        f"original={original.nunique()}, "
        f"normalized={normalized.nunique()}"
    )

first_name: original=12, normalized=12
gender: original=2, normalized=2
city: original=8, normalized=8
province: original=8, normalized=8
membership_tier: original=4, normalized=4
payment_method: original=3, normalized=3
device: original=3, normalized=3
discount_used: original=2, normalized=2

In [32]:
clean_df[[
    "age",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "last_purchase_days",
    "returned_items",
    "satisfaction_score"
]].describe()

,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,43.700000,17.383333,213.156500,3366.428833,198.600000,4.183333,2.983333
std,13.946994,10.149880,130.509923,3235.132979,97.843043,2.683861,1.431979
min,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.000000
25%,31.750000,10.750000,108.137500,1167.035000,134.250000,2.000000,2.000000
50%,45.000000,17.000000,165.435000,2128.690000,203.000000,4.000000,3.000000
75%,58.000000,24.500000,324.107500,4213.117500,273.750000,7.000000,4.000000
max,65.000000,35.000000,449.810000,14354.340000,365.000000,8.000000,5.000000

In [33]:
numeric_cols = [
    "age",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "last_purchase_days",
    "returned_items",
    "satisfaction_score"
]

for col in numeric_cols:
    Q1 = clean_df[col].quantile(0.25)
    Q3 = clean_df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = clean_df[(clean_df[col] < lower) | (clean_df[col] > upper)]
    
    print(f"{col}: {len(outliers)} outlier(s)")

age: 0 outlier(s)
purchase_count: 0 outlier(s)
avg_order_value: 0 outlier(s)
total_spending: 5 outlier(s)
last_purchase_days: 0 outlier(s)
returned_items: 0 outlier(s)
satisfaction_score: 0 outlier(s)

In [34]:
Q1 = clean_df["total_spending"].quantile(0.25)
Q3 = clean_df["total_spending"].quantile(0.75)
IQR = Q3 - Q1

clean_df[clean_df["total_spending"] > Q3 + 1.5 * IQR][
    ["customer_id", "purchase_count", "avg_order_value", "total_spending"]
]

    customer_id  purchase_count  avg_order_value  total_spending
8          1009              34           341.63        11615.42
11         1012              27           434.50        11731.50
43         1044              33           434.98        14354.34
56         1057              31           436.54        13532.74
58         1059              31           287.05         8898.55

In [35]:
text_cols = clean_df.select_dtypes(include="object").columns

for col in text_cols:
    count = clean_df[col].astype(str).str.strip().ne(clean_df[col].astype(str)).sum()
    print(f"{col}: {count}")

first_name: 0
gender: 0
city: 0
province: 0
membership_tier: 0
payment_method: 0
device: 0

In [36]:
from difflib import get_close_matches

cat_cols = [
    "gender",
    "city",
    "province",
    "membership_tier",
    "payment_method",
    "device",
    "discount_used"
]

for col in cat_cols:
    values = clean_df[col].dropna().astype(str).unique()
    found = False

    print(f"\n--- {col} ---")

    for value in values:
        matches = get_close_matches(value, values, n=3, cutoff=0.7)
        matches = [m for m in matches if m != value]

        if matches:
            print(f"{value} -> {matches}")
            found = True

    if not found:
        print("None")

--- gender ---
None

--- city ---
None

--- province ---
None

--- membership_tier ---
None

--- payment_method ---
None

--- device ---
None

--- discount_used ---
None

In [37]:
clean_df.loc[
    (clean_df["purchase_count"] > 0) & (clean_df["total_spending"] == 0)
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [38]:
clean_df.loc[
    (clean_df["purchase_count"] == 0) & (clean_df["avg_order_value"] > 0)
]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
23,1024,Sina,F,53,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.0,298,Online Wallet,Android,False,2,1

In [39]:
clean_df.loc[
    clean_df["returned_items"] > clean_df["purchase_count"]
]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
7,1008,Reza,F,23,Rasht,Gilan,2024-10-03,VIP,3,389.58,1168.74,195,Online Wallet,iPhone,False,8,1
14,1015,Kimia,F,47,Ahvaz,Khuzestan,2021-07-24,Gold,3,307.91,923.73,55,Card,Android,True,8,4
23,1024,Sina,F,53,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.00,298,Online Wallet,Android,False,2,1
28,1029,Ali,F,34,Tabriz,East Azerbaijan,2023-07-03,Gold,2,323.32,646.64,319,Cash,Web,True,4,5
36,1037,Zahra,M,42,Ahvaz,Khuzestan,2024-01-12,Gold,1,387.68,387.68,199,Cash,Web,True,7,2
55,1056,Kimia,M,61,Tabriz,East Azerbaijan,2025-01-25,Silver,1,449.81,449.81,240,Online Wallet,Web,False,4,2

In [40]:
clean_df.loc[
    (clean_df["purchase_count"] == 0) &
    (clean_df["returned_items"] == 0) &
    (clean_df["satisfaction_score"].notna())
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [41]:
clean_df.loc[
    (clean_df["discount_used"] == "Yes") & (clean_df["purchase_count"] == 0)
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [42]:
clean_df.loc[
    (clean_df["discount_used"] == "Yes") & (clean_df["avg_order_value"] == 0)
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [43]:
clean_df.loc[
    (clean_df["discount_used"] == "Yes") & (clean_df["total_spending"] == 0)
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [44]:
clean_df.loc[
    (clean_df["purchase_count"] == 0) &
    (clean_df["returned_items"] == 0) &
    (clean_df["last_purchase_days"].notna())
]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [45]:
cols = [
    "age",
    "purchase_count",
    "avg_order_value",
    "total_spending",
    "last_purchase_days",
    "returned_items"
]

for col in cols:
    print(f"{col}: {(clean_df[col] < 0).sum()}")

age: 0
purchase_count: 0
avg_order_value: 0
total_spending: 0
last_purchase_days: 0
returned_items: 0

In [46]:
clean_df["signup_date"].max()

Timestamp('2025-09-09 00:00:00')

In [47]:
for gender, group in clean_df.groupby("gender"):
    print(f"\n{gender}:")
    print(group["first_name"].to_list())

F:
['Reza', 'Parsa', 'Sina', 'Amir', 'Reza', 'Reza', 'Arash', 'Neda', 'Arash', 'Neda', 'Kimia', 'Neda', 'Parsa', 'Ali', 'Amir', 'Ali', 'Sina', 'Neda', 'Kimia', 'Mina', 'Ali', 'Neda', 'Neda', 'Sina', 'Amir', 'Sina', 'Maryam', 'Sina', 'Ali', 'Reza', 'Parsa', 'Sara', 'Reza', 'Amir', 'Ali']

M:
['Sina', 'Kimia', 'Kimia', 'Reza', 'Neda', 'Kimia', 'Reza', 'Amir', 'Sina', 'Zahra', 'Maryam', 'Arash', 'Zahra', 'Amir', 'Parsa', 'Neda', 'Kimia', 'Mina', 'Maryam', 'Arash', 'Sina', 'Mina', 'Kimia', 'Maryam', 'Ali']

In [48]:
gender_ref = pd.read_csv("persian-gender-by-name.csv")

In [49]:
gender_ref.columns

Index(['name', 'gender', 'english_name'], dtype='object')

In [50]:
clean_df["name_clean"] = (
    clean_df["first_name"]
    .str.strip()
    .str.lower()
)

gender_ref["name_clean"] = (
    gender_ref["english_name"]
    .str.strip()
    .str.lower()
)

In [51]:
check = clean_df.merge(
    gender_ref[["name_clean", "gender"]],
    on="name_clean",
    how="left"
)

In [52]:
check.columns

Index(['customer_id', 'first_name', 'gender_x', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score', 'name_clean',
       'gender_y'],
      dtype='object')

In [53]:
check.loc[
    check["gender_y"].notna() &
    (check["gender_x"] != check["gender_y"]),
    ["customer_id", "first_name", "gender_x", "gender_y"]
]

     customer_id first_name gender_x gender_y
0           1001       Reza        F        m
1           1001       Reza        F        m
2           1002       Sina        M        m
3           1003      Parsa        F        m
4           1004       Sina        F        m
..           ...        ...      ...      ...
97          1059        Ali        F        m
98          1059        Ali        F        m
99          1060        Ali        M        m
100         1060        Ali        M        m
101         1060        Ali        M        m

[95 rows x 4 columns]

In [54]:
check["gender_y"] = check["gender_y"].str.upper()

In [55]:
mask = (
    check["gender_y"].notna() &
    (check["gender_x"] != check["gender_y"])
)

In [108]:
mask = (
    check["gender_y"].notna() &
    (check["gender_x"] != check["gender_y"])
)

check.loc[mask, "gender_x"] = check.loc[mask, "gender_y"]

In [57]:
gender_map = (
    gender_ref
    .dropna(subset=["name_clean", "gender"])
    .drop_duplicates("name_clean")
    .set_index("name_clean")["gender"]
)

In [58]:
clean_df["gender_ref"] = clean_df["name_clean"].map(gender_map)

In [59]:
mask = (
    clean_df["gender_ref"].notna() &
    (clean_df["gender"] != clean_df["gender_ref"])
)

In [61]:
clean_df.loc[mask, "gender"] = clean_df.loc[mask, "gender_ref"]

In [62]:
clean_df.drop(columns=["name_clean", "gender_ref"], inplace=True)

In [68]:
print(check["gender_x"].unique())
print(check["gender_y"].unique())

['F' 'M']
['M' nan 'F']

In [70]:
check.loc[
    check["first_name"].str.lower().str.contains("kimia", na=False),
    ["first_name", "name_clean", "gender_x", "gender_y"]
]

   first_name name_clean gender_x gender_y
5       Kimia      kimia        M      NaN
11      Kimia      kimia        M      NaN
24      Kimia      kimia        F      NaN
33      Kimia      kimia        M      NaN
44      Kimia      kimia        F      NaN
70      Kimia      kimia        M      NaN
93      Kimia      kimia        M      NaN

In [71]:
gender_ref[
    gender_ref["english_name"]
    .str.lower()
    .str.contains("kimia", na=False)
][["english_name", "gender"]]

Empty DataFrame
Columns: [english_name, gender]
Index: []

In [75]:
clean_df.loc[
    clean_df["first_name"].str.strip().str.lower() == "kimia",
    "gender"
] = "f"

In [76]:
clean_df.loc[
    clean_df["first_name"].str.strip().str.lower() == "kimia",
    ["first_name", "gender"]
]

   first_name gender
4       Kimia      f
8       Kimia      f
14      Kimia      f
19      Kimia      f
26      Kimia      f
42      Kimia      f
55      Kimia      f

In [77]:
df.shape

(61, 17)

In [78]:
clean_df.info()
clean_df.describe().T

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     object
 2   gender              60 non-null     object
 3   age                 60 non-null     int64
 4   city                60 non-null     object
 5   province            60 non-null     object
 6   signup_date         60 non-null     datetime64[ns]
 7   membership_tier     60 non-null     object
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     object
 13  device              60 non-null     object
 14  discount_used       60 non-null     bool
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(6), object(7)
memory usage: 8.0+ KB

,count,mean,min,25%,50%,75%,max,std
customer_id,60.0,1030.5,1001.0,1015.75,1030.5,1045.25,1060.0,17.464249
age,60.0,43.7,19.0,31.75,45.0,58.0,65.0,13.946994
signup_date,60,2023-02-03 14:00:00,2021-02-23 00:00:00,2021-12-06 12:00:00,2022-08-15 00:00:00,2024-06-14 12:00:00,2025-09-09 00:00:00,NaN
purchase_count,60.0,17.383333,0.0,10.75,17.0,24.5,35.0,10.14988
avg_order_value,60.0,213.1565,27.63,108.1375,165.435,324.1075,449.81,130.509923
total_spending,60.0,3366.428833,0.0,1167.035,2128.69,4213.1175,14354.34,3235.132979
last_purchase_days,60.0,198.6,3.0,134.25,203.0,273.75,365.0,97.843043
returned_items,60.0,4.183333,0.0,2.0,4.0,7.0,8.0,2.683861
satisfaction_score,60.0,2.983333,1.0,2.0,3.0,4.0,5.0,1.431979

In [79]:
clean_df.to_excel("cleaned_dataset.xlsx", index=False)